"use strict";
exports.__esModule = true;
var num1 = (5);
var num2 = (3);
console.log(5 + 3);
var num3 = (4);
var num4 = (2);
var num5 = (10);
var num6 = (7);
var num7 = (64);
var num8 = (8);
console.log("".concat(num5 - num4));
console.log(4 * 2);
console.log(64 / 8);
